### ISSUE TITLE
deliver script with tarball to re-run a action locally

### ISSUE THREAD

**Issue by stefanhoelzl** [buildbarn/bb-clientd#1]
Hi,

when I want to re-run a action locally, downloaded as a tarball from bb-browser, I have to
* download&extract the tarball
* set all environment variables
* copy and run the command

this means a back and forth between bb-browser and my shell.

How about delivering a script inside the tarball which sets the env vars and runs the command?

**Comment by EdSchouten** [comment]
I think that if we want a feature like this, it should be implemented as part of bb_clientd. The advantage of doing this inside bb_clientd is that the user won't need to download anything. They can just 'cd' into the right spot and rerun an action there.

**Comment by EdSchouten** [comment]
Marking this as closed, as bb_clientd and bb_browser nowadays have decent facilities for this. Be sure to read the bb_clientd readme for details.
