### ISSUE TITLE
Using bb_clientd can break some BES features

### ISSUE THREAD

**Issue by kjteske** [buildbarn/bb-clientd#10]
When using `bb_clientd` with a remote cache, any BEP references to files stored in the remote cache, i.e. bytestream URIs, will reference `bb_clientd`'s local unix socket, rather than the real remote cache that `bb_clientd` connects to. This isn't a bug exactly; there's (currently) no way for Bazel to know what `bb_clientd` is doing, but this does limit some features built on BES, and I'd like to discuss potential improvements or workarounds.

**Problem**

More specifically, our issue is: we're using Buildbarn with the FOSS BuildBuddy UI as our `--bes_backend`; when using `bb_clientd`, the BuildBuddy UI isn't able to find the timing profile to populate the Timing tab in the UI.

The BuildBuddy UI parses BEP messages to find the timing profile URI, and can download that from the remote cache. I.e, without `bb_clientd`:
```
{
    "name": "command.profile.gz",
    "uri": "bytestream://<our real remote cache URL>/blobs/<hash>/<size>"
}
````
But when using bb_clientd:
```
{
    "name": "command.profile.gz",
    "uri": "bytestream:///home/kteske/.cache/bb_clientd/grpc/<cluster name>/blobs/<hash>/<size>"
}
```

Obviously BuildBuddy can't download the timing profile from the latter URI.

The `command.profile.gz` _is_ uploaded to the real remote cache, but Bazel itself doesn't know where that is, so it can't emit the "right" location in the BEP.

**Solutions**

We could fix this by mapping `/home/kteske/.cache/bb_clientd/grpc/` to `<remote cache URL>` in the BEP message before it gets to the BuildBuddy BES endpoint.

There are many places this mapping could be done:
- In Bazel itself (would require patch to Bazel) 
- In BuildBuddy UI (would require patch to BuildBuddy)
- A shim BES service that sits between Bazel and the BuildBuddy BES; the shim modifies bytestream URI's and forwards to the BuildBuddy BES endpoint. Would not require patching anything, but adds another component to the system.
- In `bb_clientd` - i.e. put the shim BES described above in `bb_clientd` itself.

Of these options, I like patching Bazel to enable this - this seems simplest and most generic.

This could look something like adding a new `--bes_uri_mapping` option to Bazel. Example:
```
bazel build --remote_cache=unix:/home/kteske/.cache/bb_clientd/grpc \
   --remote_instance_name=<our remote cache instance> \
   --bes_backend=<BuildBuddy BES endpoint> \
   --bes_uri_mapping=~/.cache/bb_clientd/grpc=<real remote cache URL>
```

Does this seem reasonable? We can propose a patch or MR to Bazel if this seems like the right direction.

**Comment by EdSchouten** [comment]
Have you tried using Bazel's `--remote_bytestream_uri_prefix`?

**Comment by kjteske** [comment]
D'oh! Did not see that option. That looks like exactly what we want. Would you take a PR to bb-clientd's README to recommend this?

**Comment by EdSchouten** [comment]
Sure!

**Comment by kjteske** [comment]
A little late - but put up https://github.com/buildbarn/bb-clientd/pull/12
