### ISSUE TITLE
Enable BatchStat after Bazel invocation has finished

### ISSUE THREAD

**Issue by moroten** [buildbarn/bb-clientd#3]
As a feature request, I would like to call `BatchStat` and possibly other API calls after an invocation had finished. `bazel-out/` is available through FUSE, so maybe a new interface or extension of the existing API with the use of absolute paths is enough.

**Comment by EdSchouten** [comment]
I don’t know. The Remote Output Service has been designed to work with a mutable output directory. Once a build has finished, the results ought to be immutable.

Maybe it’s better to add an API to convert an output directory to a REv2 Directory hierarchy? Then you can consume it like any other directory layout stored in the CAS.

**Comment by moroten** [comment]
In the use case for our customer is to read data after the build has completed, so `GetDirectory(outputPath)` will work.

I don't thinks it is unreasonable to want to `BatchStat` during a build as well, without knowing the `build_id`, but that can be implemented when such a use case is observed. What strikes me is that FUSE deliver the files, but there is no API to get the metadata that the FUSE directory is based on.

**Comment by moroten** [comment]
After a discussing with Ed, the conclusion was to make `bb-clientd` to serialize the resulting output directory as a [ReAPIv2 Tree message](https://github.com/bazelbuild/remote-apis/blob/3a21deee813d0b98aaeef9737c720e509e10dc8b/build/bazel/remote/execution/v2/remote_execution.proto#L1209-L1221). This can then be persisted to disk and reloaded if `bb-clientd` is restarted. This change is only a change of serialization format.

The `bb-clientd` API can then be extended to expose the tree message to external users who then can load all data from the remote content addressable storage.

**Comment by EdSchouten** [comment]
One thing I did realize: we do store a small amount of metadata alongside the output file, which we can’t easily store in a Tree… Furthermore, we currently emit the output file in a single forward pass, which would be impossible with a Tree.

Maybe if it turns out that using a Tree is undesirable for one way or another (performance), we could at least provide a conversion tool from one format to the other.

**Comment by moroten** [comment]
Maybe letting the extended API just use the existing [OutputPathPersistency](https://github.com/buildbarn/bb-remote-execution/blob/47f8d1661ef628d6bf162664d284eaf8068c3a9b/pkg/proto/outputpathpersistency/outputpathpersistency.proto) format as output.

**Comment by stagnation** [comment]
We have been thinking a little bit more on what an auxiliary service would look like.
What do you think about a new gRPC server for the protocol below.

We presume that the `instance-name` and `buildid` can be avoided,
but see that the RemoteOutputServer starts the connection with them.

```
    syntax = "proto3";                                                                                                                          [0/1668]

    package buildbarn.bbclientd_d;

    import ...

    // The Remote Output Metadata Service
    // augments the Remote Output Service
    // (and the Remote Execution API).
    // It serves the metadata for artifacts in a build
    // managed by the Remote Output Service.
    // A client can read and analyze the metadata
    // without downloading the output files and directories themselves.
    //
    // This is coupled to `bb-clientd`'s persistent state store `outputpathpersistency`.
    // As that is the only implementation at the moment.
    // So its types are used in this service.
    service RemoteOutputMetadataService {
      // The stream first opens the state file for a workspace
      // and then reads data at given offsets.
      rpc OutputMetadata(stream OutputMetadataRequest) returns (stream OutputMetadataResponse) {}
    }

    // Request metadata from an output state file,
    // this will read regions from the `outputpathpersistency` state file
    // for a workspace.
    // The first message in the stream must be `OutputMetadataInitialize`
    // to open the state file,
    // and all further messages must be `FileRegion` requests.
    //
    // The server will stream one response per request,
    // the first being the root `Directory` of the state file
    // from which the children and their `FileRegion`s can be addressed.
    // Only the children's directory names are present
    // in the `Directory` and `DirectoryNode` structs,
    // so the client must construct the full paths.
    message OutputMetadataRequest {
      message OutputMetadataInitialize {
        // A client-chosen value that uniquely identifies the workspace for
        // which the build is being started. This value must be set to ensure
        // that the remote output service is capable of managing builds for
        // distinct workspaces concurrently.
        // By default this is the MD5 sum of the absolute path of the workspace directory.
        //
        // This is the same as `StartBuildRequest.output_base_id`
        // and is described in further detail in:
        // `bb-remote-execution/pkg/proto/remoteoutputservice/remote_output_service.proto`
        // TODO(nils): How do we format references to other protos?
        string output_base_id = 1;

        // Other parameters from the Remote Output Service.
        // Are not needed here, that is part of the server's bookkeeping,
        // as the request to read a file: bazel-out/k8-fastbuild-ST-8f6eb6207b9d/bin/external/io_bazel_rules_go/stdlib_/pkg/tool/linux_amd64/cgo
        // does not have access to this data.
        // TODO(nils): remove before merging.
        //     build_id = X;
        //     instance-name = X;

        // TODO(nils): Should this be folded into the request directly?
        //             As we only have a single fields,
        //             We can refactor it later if we need more fields here.
      }

      oneof request {
        // Initial message on the stream.
        // The root directory will be returned.
        OutputMetadataInitialize open = 1;

        // Subsequent directories to read.
        // Returned in order, one for each request.
        outputpathpersistency.FileRegion directory_request = 2;
      }
    }

    message OutputMetadataResponse {
      outputpathpersistency.Directory directory = 1;
    }
```

**Comment by stagnation** [comment]
We discussed this out-of-band and think it is better and less-intrusive to create a bespoke tool that just parses the state file directly and not worry about any gRPC connections.
