### ISSUE TITLE
Build failures with native go tooling

### ISSUE THREAD

**Issue by jmmv** [buildbarn/bb-clientd#5]
I'm trying to build bb-clientd with the native Go tooling, not Bazel and I'm encountering issues. Here is what happens:

```
dev:~/os/bb-clientd/cmd/bb_clientd> git rev-parse HEAD
939beb99dc15d0673bc118d96a3ae00e179341ea

dev:~/os/bb-clientd/cmd/bb_clientd> go version
go version go1.19.5 linux/amd64

dev:~/os/bb-clientd/cmd/bb_clientd> go build
/home/jmmv/go/pkg/mod/github.com/buildbarn/bb-storage@v0.0.0-20230124100847-756fc23c9924/pkg/otel/active_spans_reporting_http_handler.go:29:13: pattern stylesheet.css: no matching files found

dev:~/os/bb-clientd/cmd/bb_clientd> sudo touch /home/jmmv/go/pkg/mod/github.com/buildbarn/bb-storage@v0.0.0-20230124100847-756fc23c9924/pkg/otel/stylesheet.css

dev:~/os/bb-clientd/cmd/bb_clientd> go build
# github.com/buildbarn/bb-storage/pkg/digest
/home/jmmv/go/pkg/mod/github.com/buildbarn/bb-storage@v0.0.0-20230124100847-756fc23c9924/pkg/digest/bare_function.go:21:18: undefined: remoteexecution.DigestFunction_SHA256TREE
/home/jmmv/go/pkg/mod/github.com/buildbarn/bb-storage@v0.0.0-20230124100847-756fc23c9924/pkg/digest/bare_function.go:63:34: undefined: remoteexecution.DigestFunction_SHA256TREE
/home/jmmv/go/pkg/mod/github.com/buildbarn/bb-storage@v0.0.0-20230124100847-756fc23c9924/pkg/digest/bare_function.go:109:23: undefined: remoteexecution.DigestFunction_SHA256TREE
```

The first failure comes from apparently a missing file in `otel`, and I guess you cannot do much about that (but for my purposes, I can workaround this as shown above).

The second failure comes from `bb-storage` trying to use a digest function that doesn't exist. I see no traces of it in the `bazelbuild/remote-build` repository, and I do not see any recent activity there.

As for why I'm doing this... because I'm trying to test a change I made to bb-remote-execution and Bazel is making this exceedingly difficult. (If you have tips on how you develop these components in unison, I'd appreciate them!)

**Comment by EdSchouten** [comment]
Sorry, but at this point we only support doing builds through bazel. The reason being that we also use it to apply patches against third party repositories. It’s not realistic for us to support two build systems.

**Comment by jmmv** [comment]
That's reasonable, but then why are `go.mod` and `go.sum` in the repo? They seem to be maintained every time there is an "Update Go dependencies" commit, which is what confused me.

In any case, I can use Bazel of course, but I'd appreciate an answer to the question at the end of my report: how can I easily build bb-clientd with a modification to a dependen local repo?

**Comment by EdSchouten** [comment]
> That's reasonable, but then why are go.mod and go.sum in the repo? They seem to be maintained every time there is an "Update Go dependencies" commit, which is what confused me.

Because we source `go_dependencies.bzl` from that file.

> In any case, I can use Bazel of course, but I'd appreciate an answer to the question at the end of my report: how can I easily build bb-clientd with a modification to a dependen local repo?

Initially, just go to `bazel-bb-clientd/external/` after doing an initial Bazel build and edit source files directly. Once you have a diff file, you can edit `go_dependencies.bzl` to automatically apply it after downloading.

**Comment by jmmv** [comment]
Ah thanks. I forgot about trying that (updating the files directly under `external`). I think we can close this!
