### ISSUE TITLE
"checking cached actions" takes way too long

### ISSUE THREAD

**Issue by jmmv** [buildbarn/bb-clientd#9]
Sometimes, I've observed that Bazel gets stuck in "checking cached actions" for a really long time (many minutes). When this happens, the machine seems idle: no CPU consumption and barely no network traffic. A jstack of Bazel shows that it's waiting on bb-clientd to finish the StartBuild (typing this name from memory from a few days ago so I may be wrong) request.

I *think* I occasionally observed similar issues before adopting bb-clientd, but these seem more common now.

I suspect bb-clientd is issuing many small requests to the build farm to check for status during this stage. High network latency (which we observe for other reasons) might explain why this is causing big delays, assuming that this is what bb-clientd is doing.

Could you advise on how to better diagnose this and/or if you have any theories on what may be happening off the top of your head?

Thank you!

**Comment by EdSchouten** [comment]
You could add something like this to you bb_clientd config:
```jsonnet
{
  global: {
    diagnosticsHttpServer: {
      listenAddress: '127.0.0.1:54321',
      enablePrometheus: true,
      enablePprof: true,
      enableActiveSpans: true,
    },
  },
}
```

Then you can go to http://localhost:54321/active_spans and see what's actually going on in that timeframe.

Every time you do a StartBuild(), bb_clientd will need to check whether all of the files stored in bazel-out/ are still present remotely. If not, it will need to remove the absent files from bazel-out/. For this to work efficiently, your build cluster needs to be very good at answering FindMissingBlobs() requests in a timely manner.

**Comment by jmmv** [comment]
Thanks for the hints. I've enabled diagnostics and will keep an eye.

My problem may actually be coming from a different issue I described in https://github.com/bazelbuild/bazel/pull/12823#issuecomment-1460438467. Feel free to close this one.
